### ISSUE TITLE
DB Migration State Removal Documentation

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-deployment#30]
Add more context to the State Removal section for when this action does and does not need to performed. 

For example, how changing the identifier will destroy the database without this being run vs if the backup is being used for a different environment.

**Comment by cdriehuys** [comment]
@Brandogs, I separated out the instructions for backing up and restoring databases and added a note as to the intended use case of the migration instructions. Let me know if more clarification is needed.
