### ISSUE TITLE
Add db removal clarification

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-deployment#31]
The documentation talks about removing a db instance from being tracked by terraform under the assumption that the db identifier is changing. If the steps in the documentation were followed, terraform would crash under the assumption that the db id is uniqued, but it would still exist in RDS.

**Comment by cdriehuys** [comment]
@Brandogs, I added a note to the top of the section discussing migrations stating the intended use case for the instructions. Feel free to re-open if you want more clarification.
